package quest;

import java.io.Serializable;

public enum QuestProceed implements Serializable {
	PROLOGUE, MAI_QUEST_1, MAI_QUEST_2, MAI_QUEST_3, MAI_QUEST_4, PARBELL_QUEST_1, PARBELL_QUEST_2, JANE_QUEST_1, DANCESWITHBALROG_QUEST_1,
	BLACKBULL_QUEST_1, BLACKBULL_QUEST_2, MANJI_QUEST_1, MANJI_QUEST_2, MANJI_QUEST_3, TENBOOGIES_QUEST_1, TENBOOGIES_QUEST_2, WINSTON_QUEST_1, 
	WINSTON_QUEST_2, STARLING_QUEST_1, STARLING_QUEST_2, STARLING_QUEST_3, DANCESWITHBALROG_QUEST_2, DANCESWITHBALROG_QUEST_3, EYAN_QUEST_1, 
	TRINA_QUEST_1, TRINA_QUEST_2, LISA_QUEST_1, LISA_QUEST_2, LISA_QUEST_3, TRINA_QUEST_3, TRINA_QUEST_4, SCADUR_QUEST_1, SERGEANTBRAVO_QUEST_1, 
	SERGEANTBRAVO_QUEST_2, ALCASTER_QUEST_1, ALCASTER_QUEST_2, TYLUS_QUEST_1, TYLUS_QUEST_2, JEFF_QUEST_1, ADOBIS_QUEST_1, ADOBIS_QUEST_2, 
	BYRON_QUEST_1, JIYUR_QUEST_1, TIGUN_QUEST_1, SEJAN_QUEST_1, SEJAN_QUEST_2;
}
