package quest;

import java.io.Serializable;

public enum QuestProceed implements Serializable {
	PROLOGUE, MAI_QUEST_1, MAI_QUEST_2, MAI_QUEST_3, MAI_QUEST_4, PARBELL_QUEST_1, PARBELL_QUEST_2, JANE_QUEST_1, DANCESWITHBALROG_QUEST_1,
	BLACKBULL_QUEST_1, BLACKBULL_QUEST_2, MANJI_QUEST_1, MANJI_QUEST_2, MANJI_QUEST_3, TENBOOGIES_QUEST_1, TENBOOGIES_QUEST_2, WINSTON_QUEST_1, 
	WINSTON_QUEST_2, STARLING_QUEST_1;
}
