package quest;

import java.io.Serializable;

public enum QuestProceed implements Serializable {
	PROLOGUE, MAI_QUEST_1, MAI_QUEST_2, MAI_QUEST_3, MAI_QUEST_4, PARBELL_QUEST_1, PARBELL_QUEST_2, JANE_QUEST_1, DANCESWITHBALROG_QUEST_1,
	BLACKBULL_QUEST_1, BLACKBULL_QUEST_2, MANJI_QUEST_1, MANJI_QUEST_2, MANJI_QUEST_3, TENBOOGIES_QUEST_1, TENBOOGIES_QUEST_2, WINSTON_QUEST_1, 
	WINSTON_QUEST_2, STARLING_QUEST_1, STARLING_QUEST_2, STARLING_QUEST_3, DANCESWITHBALROG_QUEST_2, DANCESWITHBALROG_QUEST_3, EYAN_QUEST_1, 
	TRINA_QUEST_1, TRINA_QUEST_2, LISA_QUEST_1, LISA_QUEST_2, LISA_QUEST_3, TRINA_QUEST_3, TRINA_QUEST_4, SCADUR_QUEST_1, SERGEANTBRAVO_QUEST_1, 
	SERGEANTBRAVO_QUEST_2, ALCASTER_QUEST_1, ALCASTER_QUEST_2, TYLUS_QUEST_1, TYLUS_QUEST_2, JEFF_QUEST_1, ADOBIS_QUEST_1, ADOBIS_QUEST_2, 
	BYRON_QUEST_1, JIYUR_QUEST_1, TIGUN_QUEST_1, SEJAN_QUEST_1, SEJAN_QUEST_2, ARDIN_QUEST_1, ARDIN_QUEST_2, ARDIN_QUEST_3, JANO_QUEST_1, 
	SIRIN_QUEST_1, AREDA_QUEST_1, SHEHERAZARD_QUEST_1, SIRIN_QUEST_2, BYRON_QUEST_2, HANBROKER_QUEST_1, HANBROKER_QUEST_2, KEENY_QUEST_1,
	KEENY_QUEST_2, MAED_QUEST_1, RUSSELLON_QUEST_1, RUSSELLON_QUEST_2, RUSSELLON_QUEST_3, RUSSELLON_QUEST_4, CARSON_QUEST_1, BEDIN_QUEST_1, 
	BEDIN_QUEST_2, BEDIN_QUEST_3, PHYLLIA_QUEST_1, BEDIN_QUEST_4, CARSON_QUEST_2, CARSON_QUEST_3, KUPO_QUEST_1, KUPO_QUEST_2, KUPO_QUEST_3, 
	DAME_QUEST_1, DAME_QUEST_2, DAME_QUEST_3, MYSTERIOUSMAGIC_QUEST_1, DAME_QUEST_4, TATAMO_QUEST_1, KOSCU_QUEST_1, KOSCU_QUEST_2, KOSCU_QUEST_3, 
	CROW_QUEST_1, ATHENA_QUEST_1, TEMPLEKEPPER_QUEST_1, TEMPLEKEPPER_QUEST_2, TEMPLEKEPPER_QUEST_3, TEMPLEKEPPER_QUEST_4, TEMPLEKEPPER_QUEST_5, 
	TEMPLEKEPPER_QUEST_6, TEMPLEKEPPER_QUEST_7;
}
